version: '3'

volumes:
  production_sql_data: {}
  production_sql_data_backups: {}
  production_traefik: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: sidgro_production_django
    depends_on:
      - sqlserver
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.sqlserver
    command: /start


  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    container_name: sqlserver
    user: '0:0'
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "PasswordO1."
      MSSQL_PID: Express
    volumes:
      - production_sql_data:/var/opt/mssql/data:Z
      - production_sql_data_backups:/backups:z


  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: sidgro_production_traefik
    depends_on:
      - sqlserver
    volumes:
      - production_traefik:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:5555:5555"

  redis:
    image: redis:5.0

  celeryworker:
    <<: *django
    image: sidgro_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: sidgro_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: sidgro_production_flower
    command: /start-flower

  awscli:
    build:
      context: .
      dockerfile: ./compose/production/aws/Dockerfile
    env_file:
      - ./.envs/.production/.django
    volumes:
      - production_sql_data_backups:/backups:z
